  # Create a Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref HittVPC
      CidrBlock: "10.0.1.0/22" # Range: 10.0.1.1 to 10.0.4.255, Usable Total IP addresses: 10,22
      # (index 0) from the list returned by !GetAZs 
      AvailabilityZone: !Select [0, !GetAZs ""] 
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PublicSubnet