  # Create a VPC
  HittVPC:
    Type: AWS::EC2::VPC
     Properties:
      CidrBlock: "10.0.0.0/22" # (medium size network) Range: 10.0.0.0 to 10.0.255.255, Usable Total IP addresses: 10,22
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: FridayHITT_VPC
   